trailingComma: 'es5'
tabWidth: 2
semi: true
singleQuote: true
importOrder: 
  - '<THIRD_PARTY_MODULES>'
  - '.*services\/.*'
  - '^\.+\/.*'
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrderCaseInsensitive: true
plugins:
  - '@trivago/prettier-plugin-sort-imports'
